---
title: "Purr Eval"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(12L)
```

```{r}
library(tidyverse)
library(broom)
```

## Map

```{r}
c(1,2,3) %>% map(function(a) a^0.5)
```


```{r}
c(1,2,3) %>% map(function(a) {a^0.5})
```

```{r}
c(1,2,3) %>% map(sqrt)
```

```{r}
tibble(a=c(4,3,5), b=c(8,9,5)) %>%  map(sqrt)
```

```{r}
c(1,2,3) %>% map(~sqrt(.))
```

## Map2

```{r}
map2(c(1,3), c(4,8), function(a,b) a*b)
```

```{r}
map2(c(1,3), c(4,8), ~(..1)*(..2))
```

```{r}
c(1,3) %>% map2(c(4,8), ~(..1)*(..2))
```

## Multiple features

```{r}
list(list(5, 27, 50), list(1000, 1000, 1000)) %>%
  pmap(function(a,b)a*b)
```
```{r}
list(list(5, 27, 50), list(1000, 1000, 1000), list(10, 2, 90)) %>% 
  pmap(~(..1)*(..2)*(..3))
```
```{r}
tibble(
  a = c(5, 27, 50),
  b = c(1000, 1000, 1000),
  c = c(10, 2, 90)
) %>%
  pmap( ~ (..1) * (..2) * (..3))
```
```{r}
tibble(
  a = c(5, 27, 50),
  b = c(1000, 1000, 1000),
  c = c(10, 2, 90),
  d = c(9, 5, 1)
) %>%
  pmap( ~ with(list(...), a * b * c * d))
```

```{r}
library(glue)
tibble(
  a = c(5, 27, 50),
  b = c(1000, 1000, 1000),
  c = c(10, 2, 90)
) %>%
  pmap(~ "a: {..1},  b:{..2}, c:{..3}" %>% glue())
```

```{r}
tibble(
  a = c(5, 27, 50),
  b = c(1000, 1000, 1000),
  c = c(10, 2, 90),
  d = c(9, 2, 8)
) %>%
  pmap(~ with(list(...),"a: {a},  b:{b}, c:{c}, d:{d}" %>% glue()))
```


```{r}
multiply <- function(a, b) {
  a * b
}
```

```{r}
list(list(5, 27, 50), list(1000, 1000, 1000)) %>%
  pmap( ~ multiply(..1, ..2))
```

## Other examples with broom

```{r}
data <-  tibble(group = "1",
                a = runif(10, 1, 1000),
                b = runif(10, 1, 1000)) %>%
  bind_rows(tibble(
    group = "2",
    a = runif(10, 1, 1000),
    b = runif(10, 1, 1000)
  )) %>%
  bind_rows(tibble(
    group = "3",
    a = runif(10, 1, 1000),
    b = runif(10, 1, 1000)
  ))
```

```{r}
plot_fit <- function(data) {
  data %>% 
    ggplot(aes(x = a)) +
    geom_point(aes(y = b)) +
    geom_line(aes(y = .fitted), color = "blue") 
}
```


```{r}
data <- data %>%
  group_by(group) %>%
  nest() %>%
  mutate(
    pca = map(data, ~ prcomp(., center = T, scale = T)),
    loess = map(data, ~ loess(a ~ b, .)),
    lm = map(data, ~ lm(a ~ b, .)),
    loess_augmented = map(loess, augment),
    lm_tidy = map(lm, tidy),
    lm_glance = map(lm, glance),
    lm_augmented = map(lm, augment),
    pca_augmented = map2(pca, data,   ~ augment(.x, data = .y)),
    pca_tidy = map2(pca, data, ~ augment(.x, data = .y)),
    loess_plot= map(loess_augmented, ~plot_fit(.)),
    lm_plot = map(lm_augmented, ~plot_fit(.))
  ) %>% 
  ungroup()
```
`

```{r}
data %>% pull(lm_plot)
```

```{r}

data %>% pull(loess_plot)
```

